### ISSUE TITLE
Rendering is broken with `glib2-2.72`

### ISSUE THREAD

**Issue by cheap-glitch** [AndrewRadev/quickmd#15]
After upgrading `glib2` to the `2.72` version, the preview window became completely blank. `quickmd --debug` doesn't produce any errors. Downgrading the package fixed the issue.

Edit: This is on Arch Linux with Wayland.

**Comment by AndrewRadev** [comment]
Hm, that's not great. I seem to have glib2 at the same version, but it's working for me:

```
% pacman -Qs glib2 
local/glib2 2.72.0-1
    Low level core library
```

I'm also on Arch, but I'm not using wayland. Is the compiled binary breaking for you or `cargo run` breaks too? If you `cargo clean` to make sure all the packages are rebuilt, does the problem persist?

**Comment by Euro20179** [comment]
I have a similar problem. Pacman says I'm on glib2 2.72.0-1.

It's broken on bspwm (x11), river, and sway

I'm not sure when it broke because it happened a long time ago and thought it was just me.

The only thing I can say that might be of help is that the generated html file is not empty, and is correct. It's just the rendering that's broken.

The precompiled binary is broken, I just installed with `cargo install --force quickmd` also broken.


debug info:
```
[DEBUG quickmd] Loaded config: Config { zoom: 1.0, editor_command: [], mappings: [] }
[DEBUG quickmd]   > path: /home/euro/.config/quickmd/config.yaml
[DEBUG quickmd] Using input options: Options { debug: true, input_file: Some("-"), watch: true, output_dir: None, install_default_config: false }
[DEBUG quickmd::assets] Building HTML:
[DEBUG quickmd::assets]  > custom_css_path = "/home/euro/.config/quickmd/custom.css"
[DEBUG quickmd::assets]  > page_state      = "{\"scroll_top\":0.0,\"image_widths\":{},\"image_heights\":{}}"
[DEBUG quickmd::assets]  > code languages  = {"sh"}
[DEBUG quickmd::ui] Loading HTML:
[DEBUG quickmd::ui]  > output_path = /tmp/.tmpMGbXWN/index.html
```

The config file just has `zoom: 1.0` in it because i wanted to see if creating a config would fix it. I have no css file.

**Comment by Euro20179** [comment]
Alright i've tried a few different things.

1. I downgraded webkit2gtk to 2.34.something, and it didn't work. 
2. I then tried recompiling quickmd (with the downgraded webkit), it didn't work
3. I then logged into bspwm with my newly compiled quickmd, and it didn't work. But gtk gave me this error: 
4. I upgraded webkit2gtk, and now quickmd is still blank, but instead of a dark grey (i believe this is my gtk theme) it's white.
5. I recompiled quickmd again, and still broken, gtk messages still there.

In the issue cheap-glitch posted, they mentioned you need xdg-desktop-portal, which I have.

**Comment by AndrewRadev** [comment]
@Euro20179 One of the things in that bug thread (Thanks, @cheap-glitch!) is `WEBKIT_DISABLE_COMPOSITING_MODE=1`, which seems to fix the issue by disabling hardware compositing (I guess that would mean it's somehow an issue with specific video cards?). Could you try that one as well? For that matter, @cheap-glitch, does `WEBKIT_DISABLE_COMPOSITING_MODE=1 quickmd <filename>` do anything for you?

**Comment by Euro20179** [comment]
I actually did try that, but forgot to mention it, but no it doesn't fix the problem.

**Comment by AndrewRadev** [comment]
Unfortunately, I don't have any more idea what I could do to fix the problem. If I could replicate the issue, I'd try to experiment with the versions of the rust bindings of webkit2gtk, gtk, etc, see if there's some configuration that avoids the issue. Though if the problem is in webkit2gtk itself, it probably wouldn't have helped.

If I were to use webkit through a different project (I was thinking of it at some point https://github.com/AndrewRadev/quickmd/issues/10), this might avoid problems, but it's going to be a large undertaking. I'll see if I can devote a weekend to it.

In terms of usability, there's still the option to generate the HTML files and just open them in a default browser. I'm thinking of whether it'd be possible to add a command-line flag for "generate and open in browser", the problem is the tmp directory where the assets would have to not be cleaned up, or maybe the tool would have to block until a keypress or something... It's a bit weird in terms of user experience 😅.

**Comment by cheap-glitch** [comment]
Seems to me that this is a bug introduced in the latest version of webkit, so we might be stuck waiting for an internal patch to fix this.

In the meantime, I like the idea of opening the preview in a browser. If that's okay with you @AndrewRadev I can work on adding a `--browser` flag that would to just that.

> the problem is the tmp directory where the assets would have to not be cleaned up

As long as we keep the same filename in a single "session", we can get away with having to press <kbd>F5</kbd> to reload the preview.

With a local server, websockets and a touch of JS we could even have the page automatically reload, but that'd require a bit more work (and dependencies).

**Comment by Euro20179** [comment]
Im good with viewing in my browser, a --browser option would be nice, but my bigger concern is getting the github css in the browser preview

**Comment by AndrewRadev** [comment]
@Euro20179 The github CSS is not a problem. Right now, without any changes, you can execute: `quickmd <markdown-file> --output output_dir` and then exit the app and open `output_dir/index.html` in your browser and you'll get a rendered HTML file with the same CSS as the app itself. The problem is more about how to handle the flow.

@cheap-glitch I've created a branch where I added a `--browser-only` flag that outputs the filename and then I guess you could copy it into the browser: [browser-only-workaround](https://github.com/AndrewRadev/quickmd/tree/browser-only-workaround)

Let me know what you think, both of you, it's a bit of a hack, but at least it'll work for now, I think. There's other, more featureful solutions that use the browser, and I feel like it'd be pointless to try and match them for feature parity, my entire reason for creating quickmd is that it's self-contained and this kind of breaks the idea 😅. But if it's a valid workaround until there's a webkit2gtk patch, I think that's fine.

**Comment by Euro20179** [comment]
Quite honestly i have NO IDEA what changed, but this is no longer an issue for me. I'm glad I get to use this program again, I had been using instant-markdown for vim as a substitute but it's more inconvenient.

**Comment by cheap-glitch** [comment]
It's fixed for me too! I guess this can be closed now :smiley:

**Comment by AndrewRadev** [comment]
My favorite kind of issue is the one that fixes itself :D. Glad to hear things are fine now :+1:
