### ISSUE TITLE
Customizable keybindings

### ISSUE THREAD

**Issue by AndrewRadev** [AndrewRadev/quickmd#5]
It would be really nice if it was possible to customize keybindings for spawning an editor, for scrolling, etc.

It could be implemented the way Alacritty does it:

```
  - { key: Insert, mods: Shift, action: PasteSelection   }
```

Alternatively, I'd love to have vim-like `<S-Insert>` descriptions of keys, which are pretty compact and readable (though I might be biased here).

**Comment by cheap-glitch** [comment]
It's not very vim-like, but I'd love to be able to press `q` to quit. It would match the behavior of other lightweight "document viewers" that I use (for images, PDFs, etc.)

**Comment by AndrewRadev** [comment]
> Is this an actual bug, or was it removed but the readme wasn't updated?

I've missed it in the README, I'll give it a refresh once I'm done with the changes.

**Comment by cheap-glitch** [comment]
> Could you try it out and let me know if it makes sense to you?

It works well!

Some quick notes/ideas:
- It should be possible to omit `modifiers` entirely. Right now this causes a parsing error.

- `key_name` values should probably be normalized, so that e.g. both "escape" and "Escape" work (right now only the second does).

- In fact, it would be nicer to just have a single attribute named `key` like in Alacritty's config, instead of having to choose between `key_name`/`key_char`. Though I don't know how tricky it would be for the code to guess which one the user meant.

- And, since you're imitating the format of Alacritty's config anyway, why not reuse it's nocemclature directly? So `mods` instead of `modifiers`, etc. Unless you feel it's not clear or explicit enough.

All of these are only minor quibbles or "would-be-nice-to-have" features, it still does the job well enough :+1:

**Comment by AndrewRadev** [comment]
> It should be possible to omit modifiers entirely. Right now this causes a parsing error.

Yeah, that's true, fixed.

> And, since you're imitating the format of Alacritty's config anyway, why not reuse it's nocemclature directly? So mods instead of modifiers, etc. Unless you feel it's not clear or explicit enough.

"Mods" sounds good enough to me :+1: 

> key_name values should probably be normalized, so that e.g. both "escape" and "Escape" work (right now only the second does).

The problem with this is that there doesn't seem to be a consistent normalization. If it was just about lowercasing, that'd be fine, but "Escape" works where "Minus" doesn't -- it's "minus". Really, the core problem both with this and the common "Key" prop is that I'm just delegating to GDK trying to do as little special work as possible 😅. Not just because of the extra work, but also because I don't know about subtleties that GDK handles, like `=` is actually shift + `+`, for example, but is that going to be the same on non-qwerty keyboards? I feel like I'd rather just give whatever comes in to GDK and tackle problems as they come in, which is why I opted to do it both ways.

Using `name` universally would work for the alphabetic keys, I think, but it wouldn't work for `+`, `-`, I don't know what else. For now, I'd rather not touch this part. Maybe I'll come back to it later.

**Comment by AndrewRadev** [comment]
I've merged the branch and cut a new release, I added your PR as well (sorry again for missing it). With this, I'll close this issue for the moment. Feel free to reopen if you find any bugs or want to discuss changes, or you could open a new one.
